[build-system]
requires = ["setuptools", "wheel", "pybind11"]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
build = "cp311-*"
skip = "*-musllinux*" 

[project]
name = "lisptorch"
version = "0.1.10" 
